dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.4.2
    - smartcontractkit/chainlink-brownie-contracts@0.4.0
compiler:
    solc:
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"

dotenv: .env
wallets:
    from_key: ${PRIVATE_KEY}

networks:
    development:
        verify: False
    ganache:
        verify: False
    goerli:
        verify: True
        weth_token: "0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6"
        dai_token: "0x88271d333C72e51516B67f5567c728E702b3eeE8" #Dai
        eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
        dai_usd_price_feed: "0x0d79df66BE487753B02D015Fb622DED7f0E9798d"
